<h1 style="color:#ff5733; text-align:center; font-size:45px;">🚀 Hello! I'm <b style="color:#33A1FF;">Yahya Ahmad</b> 👋</h1>

<p style="font-size:22px; text-align:center; color:#444;">
I'm a beginner passionate about <b style="color:#FF914D;">technology</b>, <b style="color:#FF914D;">machine learning</b>, and <b style="color:#FF914D;">Python programming</b>. 
I'm excited to learn and grow in the world of <b style="color:#33A1FF;">data science</b> and <b style="color:#33A1FF;">AI</b>. 🚀
</p>

<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#33A1FF; font-size:30px;">🎯 My Interests:</h2>

<ul style="font-size:22px; color:#444;">
    <li><b style="color:#FF914D;">Programming</b>: Python </li>
    <li><b style="color:#FF914D;">Machine Learning</b>: Exploring PyTorch and TensorFlow</li>
    <li><b style="color:#FF914D;">Deep Learning AI</b>: Neural Networks & Computer Vision</li>
</ul>

<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#33A1FF; font-size:30px;">📬 Let's Connect!</h2>

<ul style="font-size:22px; color:#444;">
    <li>📧 <b>Email</b>: <a href="mailto:Ya0280780@gmail.com" style="color:#FF914D;">Ya0280780@gmail.com</a></li>
    <li>🔗 <b>LinkedIn</b>: <a href="https://www.linkedin.com/in/yahya-ahmad-8538312b1/" style="color:#FF914D;">Yahya Ahmad on LinkedIn</a></li>
    <li>💻 <b>GitHub</b>: <a href="https://github.com/Yahyaahmad09/Courses" style="color:#FF914D;">My GitHub Repository</a></li>
</ul>

<hr style="border:2px solid #ff5733; width:80%;">


<h1 style="color:#E74C3C; text-align:center; font-size:45px;">🔥 Introduction to PyTorch 🔥</h1>

<p style="font-size:22px; text-align:center; color:#444;">
<b>PyTorch</b> is a powerful, open-source deep learning framework that has become a popular choice for researchers and developers. 
It provides flexible tools for building and training neural networks, making it a key player in the field of 
<b style="color:#E74C3C;">Artificial Intelligence (AI)</b> and <b style="color:#E74C3C;">Machine Learning (ML)</b>.
</p>

<p style="color: #3498db; font-size: 20px; text-align:center;"><i>Whether you are a beginner or an experienced machine learning practitioner, PyTorch offers everything you need to build and experiment with models easily and efficiently.</i></p>

<hr style="border:2px solid #E74C3C; width:80%;">

<h2 style="color:#3498db; font-size:30px;">✨ Key Features of PyTorch</h2>

<ul style="font-size:22px; color:#444;">
    <li><b style="color:#E67E22;">Dynamic Computational Graphs</b>: PyTorch uses dynamic computation graphs, making it easy to change the model architecture during runtime.</li>
    <li><b style="color:#E67E22;">GPU Acceleration</b>: PyTorch supports GPU computation, speeding up the training process significantly for large models.</li>
    <li><b style="color:#E67E22;">Easy-to-Use API</b>: With a Pythonic API, PyTorch is simple to learn and integrate with other tools.</li>
</ul>

<hr style="border:2px solid #E74C3C; width:80%;">

<h2 style="color:#3498db; font-size:30px;">🚀 Why Choose PyTorch?</h2>

<p style="font-size:22px; color:#444;">
PyTorch's flexibility and ease of use make it an ideal framework for experimentation and development, especially for tasks like:
</p>

<ul style="font-size:22px; color:#444;">
    <li>💡 <b style="color:#E67E22;">Deep Learning</b>: Build and train neural networks from scratch.</li>
    <li>🖼️ <b style="color:#E67E22;">Computer Vision</b>: Leverage pre-trained models and work on image-related tasks.</li>
    <li>📝 <b style="color:#E67E22;">Natural Language Processing (NLP)</b>: Implement state-of-the-art language models and more.</li>
</ul>

<p style="background-color: #f2f2f2; font-size: 18px; padding: 15px; border-radius: 8px; color:#444;">
<b>PyTorch has quickly gained popularity</b> due to its intuitive design and seamless integration with Python's scientific computing ecosystem.
</p>

<hr style="border:2px solid #E74C3C; width:80%;">

<h2 style="color:#3498db; font-size:30px;">🛠️ Let's Get Started!</h2>

<p style="font-size:22px; color:#444;">
In this notebook, we will cover the basics of PyTorch, including how to:
</p>

<ul style="font-size:22px; color:#444;">
    <li>📌 Work with <b style="color:#E67E22;">Tensors</b></li>
    <li>📌 Build simple <b style="color:#E67E22;">Neural Networks</b></li>
    <li>📌 Train and evaluate <b style="color:#E67E22;">Models</b></li>
</ul>

<p style="text-align:center; font-size:24px; color:#E74C3C;"><b>Let's dive in! 🚀</b></p>

<hr style="border:2px solid #E74C3C; width:80%;">


<h1 style="color:#3498db; text-align:center; font-size:45px;">⚡ Importing PyTorch</h1>

<p style="font-size:22px; color:#444; text-align:center;">
To begin working with PyTorch, you first need to import the <b style="color:#FF914D;">torch</b> library into your Python environment.
You can do this using the following code:
</p>

<hr style="border:2px solid #3498db; width:80%;">

<h2 style="color:#3498db; font-size:30px;">🔑 Code to Import PyTorch</h2>

<p style="font-size:20px; background-color:#f2f2f2; padding:15px; border-radius:8px; color:#444;">
<b style="color:#E67E22;">import torch</b>
</p>

<p style="font-size:20px; text-align:center; color:#444;">
Once the <b style="color:#FF914D;">torch</b> library is imported, you can start using its features for deep learning tasks.
</p>

<hr style="border:2px solid #3498db; width:80%;">

<h2 style="color:#3498db; font-size:30px;">🚀 Let's Get Started!</h2>

<p style="font-size:22px; color:#444;">
Now that you've successfully imported PyTorch, you're ready to start experimenting with Tensors, neural networks, and more!
</p>

<p style="text-align:center; font-size:24px; color:#E74C3C;"><b>Happy Coding! 🚀</b></p>

<hr style="border:2px solid #3498db; width:80%;">


In [181]:
import torch

<h1 style="color:#E74C3C; text-align:center; font-size:40px;">🔢 Tensors in PyTorch</h1>

<p style="font-size:22px; color:#444; text-align:center;">
A <b style="color:#FF914D;">tensor</b> is a multi-dimensional array, which is the core data structure in PyTorch. 
Tensors are similar to <b style="color:#FF914D;">NumPy arrays</b>, but they can run on <b style="color:#3498db;">GPU</b> for faster computation, making them essential for deep learning tasks.
</p>

<hr style="border:2px solid #E74C3C; width:80%;">

<h2 style="color:#3498db; font-size:30px;">✨ Key Features of Tensors</h2>

<ul style="font-size:22px; color:#444;">
    <li><b style="color:#E67E22;">Multi-dimensional</b>: Tensors can be 0D (scalars), 1D (vectors), 2D (matrices), or higher-dimensional (like images or video frames).</li>
    <li><b style="color:#E67E22;">GPU Support</b>: Tensors can be moved to a <b style="color:#3498db;">GPU</b> to accelerate computation, making them essential for training deep neural networks.</li>
    <li><b style="color:#E67E22;">Flexible Operations</b>: PyTorch allows for a wide range of operations on tensors, such as mathematical functions, element-wise operations, reshaping, slicing, and more.</li>
</ul>

<hr style="border:2px solid #E74C3C; width:80%;">

<h2 style="color:#3498db; font-size:30px;">🚀 Let's Create a Tensor</h2>

<p style="font-size:22px; text-align:center; color:#444;">
Now that you know about tensors, let's create one and explore its properties.
</p>

<hr style="border:2px solid #E74C3C; width:80%;">


<h1 style="color:#FF914D; text-align:center; font-size:35px;">🚀 Creating Tensors with PyTorch</h1>

<p style="font-size:12px; color:#444; text-align:center;">
In PyTorch, a <b style="color:#E67E22;">tensor</b> is the fundamental data structure, similar to an array in NumPy but with additional capabilities like <b style="color:#3498db;">GPU support</b>. PyTorch provides several ways to create tensors.
</p>

<hr style="border:2px solid #FF914D; width:70%;">

<h2 style="color:#3498db; font-size:20px; text-align:center;">✨ Ways to Create Tensors</h2>

<ul style="font-size:18px; color:#444; list-style-position: inside;">
    <li><b style="color:#E67E22;">From a List or NumPy Array</b>: You can create a tensor from a list or a NumPy array.</li>
    <li><b style="color:#E67E22;">With Random Values</b>: Use <b style="color:#3498db;">torch.rand()</b> or <b style="color:#3498db;">torch.randn()</b> for random values.</li>
    <li><b style="color:#E67E22;">With Zeros or Ones</b>: Use <b style="color:#3498db;">torch.zeros()</b> or <b style="color:#3498db;">torch.ones()</b>.</li>
    <li><b style="color:#E67E22;">From Existing Data</b>: Create tensors from images, text, or other data.</li>
</ul>

<hr style="border:2px solid #FF914D; width:70%;">

<h2 style="color:#3498db; font-size:24px; text-align:center;">🧑‍💻 Let's Create a Simple Tensor</h2>

<p style="font-size:18px; text-align:center; color:#444;">
Now, let's create a simple tensor and examine its properties!
</p>

<hr style="border:2px solid #FF914D; width:70%;">


In [16]:
# using empty
a =  torch.empty(2,3)

In [18]:
# type
type(a)

torch.Tensor

In [5]:
# using Zeros
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using Ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using eye (identity matrics)
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [9]:
# using rand
torch.rand(3,4)

tensor([[0.4925, 0.9664, 0.5399, 0.0296],
        [0.6162, 0.4501, 0.7501, 0.6083],
        [0.8562, 0.9458, 0.0505, 0.0459]])

In [11]:
# uing seed()
torch.seed()
torch.rand(3,3)

tensor([[0.7713, 0.6872, 0.1526],
        [0.8672, 0.1088, 0.2135],
        [0.4261, 0.3654, 0.1990]])

In [19]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
# using arange
torch.arange(3,15,2)

tensor([ 3,  5,  7,  9, 11, 13])

In [24]:
# using linespace
torch.linspace(2,20,15)

tensor([ 2.0000,  3.2857,  4.5714,  5.8571,  7.1429,  8.4286,  9.7143, 11.0000,
        12.2857, 13.5714, 14.8571, 16.1429, 17.4286, 18.7143, 20.0000])

In [25]:
#  using full
torch.full((3,3),4)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

<h1 style="font-size: 30px; color: #2c3e50; font-weight: bold;">📏 Tensor Shape in PyTorch</h1>

<p style="font-size: 18px; color: #34495e;">
  A <strong>tensor's shape</strong> defines its dimensions and the number of elements in each dimension. 
  Understanding tensor shapes is essential when working with deep learning models and mathematical operations in PyTorch.
</p>

<h3 style="font-size: 22px; color: #16a085;">🔹 Checking the Shape of a Tensor</h3>

<p style="font-size: 18px; color: #34495e;">
  You can check the shape of a tensor using the <code style="font-size: 18px; background-color: #ecf0f1; padding: 3px;">.shape</code> or <code style="font-size: 18px; background-color: #ecf0f1; padding: 3px;">.size()</code> attribute:
</p>


<p style="font-size: 18px; color: #34495e;">
  The <code>.shape</code> attribute returns the dimensions of the tensor, while <code>.size()</code> also gives the same result.
</p>


In [30]:
y = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,15,20]])

In [31]:
y

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 15, 20]])

In [32]:
# using shape
y.shape

torch.Size([4, 3])

In [35]:
# for reshaping use (reshape)
y.reshape(3,4)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 15, 20]])

In [43]:
# using zeros like
torch.zeros_like(y)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [44]:
# using ones like
torch.ones_like(y)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [45]:
# using rand like 
torch.rand_like(y, dtype = float)   # but here it is essential to specify the data type otherwise it give error

tensor([[0.0546, 0.2886, 0.3626],
        [0.6403, 0.5733, 0.0200],
        [0.7794, 0.9245, 0.7784],
        [0.4173, 0.0116, 0.9541]], dtype=torch.float64)

<h1 style="font-size: 20px; color: #2980b9; font-weight: bold;">🔢 Tensor Data Types in PyTorch</h1>

<p style="font-size: 12px; color: #2c3e50;">
  In PyTorch, tensors support different <strong>data types</strong> to control precision, memory usage, and performance. 
  Choosing the right data type is important for speed optimization and numerical accuracy.
</p>

<h3 style="font-size: 15px; color: #1abc9c;">🔹 Checking the Data Type of a Tensor</h3>

<p style="font-size: 12px; color: #34495e;">
  You can check a tensor's data type using the <code style="font-size: 18px; padding: 3px;">.dtype</code> attribute:
</p>

<pre style="font-size: 18px; color: #2c3e50; background-color: #ecf0f1; padding: 10px;">

<p style="font-size: 18px; color: #34495e;">
  The <code>.dtype</code> attribute gives you the data type of the tensor, which can be important for understanding precision 
  and ensuring your model is optimized correctly.
</p>


In [37]:
# find data type
y.dtype

torch.int64

In [39]:
# assign data type   (when store in integer)
torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]],dtype = torch.int64)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [41]:
# assign data type  (when store in float)
torch.tensor([[1,2,3],[4,5,6]],dtype = torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [42]:
# using to() (to convert into  float or integer)
y.to(torch.float32)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 15., 20.]])

<h1 style="color:#ff5733; text-align:center; font-size:35px;">🧮 Mathematical Computations in PyTorch</h1>

<hr style="border:2px solid #ff5733;">

<h2 style="color:#33A1FF; font-size:25px;">1️⃣ Basic Arithmetic Operations</h2>
<ul style="font-size:18px;">
    <li><b style="color:#FF914D;">Addition</b> → <code>+</code>, <code>torch.add()</code></li>
    <li><b style="color:#FF914D;">Subtraction</b> → <code>-</code>, <code>torch.sub()</code></li>
    <li><b style="color:#FF914D;">Multiplication</b> → <code>*</code>, <code>torch.mul()</code></li>
    <li><b style="color:#FF914D;">Division</b> → <code>/</code>, <code>torch.div()</code></li>
</ul>

<h2 style="color:#33A1FF; font-size:25px;">2️⃣ Advanced Mathematical Functions</h2>
<ul style="font-size:18px;">
    <li><b style="color:#FF914D;">Exponentiation</b> → <code>torch.exp()</code></li>
    <li><b style="color:#FF914D;">Square Root</b> → <code>torch.sqrt()</code></li>
    <li><b style="color:#FF914D;">Logarithm</b> → <code>torch.log()</code></li>
    <li><b style="color:#FF914D;">Power</b> → <code>torch.pow()</code></li>
</ul>

<h2 style="color:#33A1FF; font-size:25px;">3️⃣ Matrix Operations</h2>
<ul style="font-size:18px;">
    <li><b style="color:#FF914D;">Matrix Addition</b> → <code>+</code>, <code>torch.add()</code></li>
    <li><b style="color:#FF914D;">Matrix Multiplication</b> → <code>torch.matmul()</code>, <code>@</code></li>
    <li><b style="color:#FF914D;">Transpose</b> → <code>.T</code>, <code>torch.transpose()</code></li>
    <li><b style="color:#FF914D;">Inverse</b> → <code>torch.inverse()</code></li>
</ul>

<h2 style="color:#33A1FF; font-size:25px;">4️⃣ Reduction Operations (Sum, Mean, Max, Min)</h2>
<ul style="font-size:18px;">
    <li><b style="color:#FF914D;">Summation</b> → <code>torch.sum()</code></li>
    <li><b style="color:#FF914D;">Mean/Average</b> → <code>torch.mean()</code></li>
    <li><b style="color:#FF914D;">Maximum</b> → <code>torch.max()</code></li>
    <li><b style="color:#FF914D;">Minimum</b> → <code>torch.min()</code></li>
</ul>

<h2 style="color:#33A1FF; font-size:25px;">5️⃣ Element-wise vs. Matrix-wise Computations</h2>
<ul style="font-size:18px;">
    <li><b style="color:#FF914D;">Element-wise Operations</b></li>
    <li><b style="color:#FF914D;">Matrix-wise Operations</b></li>
</ul>

<h2 style="color:#33A1FF; font-size:25px;">6️⃣ Broadcasting in PyTorch</h2>
<ul style="font-size:18px;">
    <li><b style="color:#FF914D;">Automatic Expansion of Tensors</b></li>
</ul>

<h2 style="color:#33A1FF; font-size:25px;">7️⃣ Special Functions</h2>
<ul style="font-size:18px;">
    <li><b style="color:#FF914D;">Sine & Cosine</b> → <code>torch.sin()</code>, <code>torch.cos()</code></li>
    <li><b style="color:#FF914D;">Hyperbolic Functions</b> → <code>torch.tanh()</code>, <code>torch.sinh()</code>, <code>torch.cosh()</code></li>
    <li><b style="color:#FF914D;">Absolute Value</b> → <code>torch.abs()</code></li>
</ul>

<h2 style="color:#33A1FF; font-size:25px;">8️⃣ Comparison Operations</h2>
<ul style="font-size:18px;">
    <li><b style="color:#FF914D;">Equal to</b> → <code>==</code>, <code>torch.eq()</code></li>
    <li><b style="color:#FF914D;">Not Equal to</b> → <code>!=</code>, <code>torch.ne()</code></li>
    <li><b style="color:#FF914D;">Greater than</b> → <code>></code>, <code>torch.gt()</code></li>
    <li><b style="color:#FF914D;">Greater than or Equal to</b> → <code>>=</code>, <code>torch.ge()</code></li>
    <li><b style="color:#FF914D;">Less than</b> → <code><</code>, <code>torch.lt()</code></li>
    <li><b style="color:#FF914D;">Less than or Equal to</b> → <code><=</code>, <code>torch.le()</code></li>
</ul>

<h2 style="color:#33A1FF; font-size:25px;">9️⃣ In-Place Operations</h2>
<ul style="font-size:18px;">
    <li><b style="color:#FF914D;">Addition (in-place)</b> → <code>torch.add_()</code></li>
    <li><b style="color:#FF914D;">Subtraction (in-place)</b> → <code>torch.sub_()</code></li>
    <li><b style="color:#FF914D;">Multiplication (in-place)</b> → <code>torch.mul_()</code></li>
    <li><b style="color:#FF914D;">Division (in-place)</b> → <code>torch.div_()</code></li>
    <li><b style="color:#FF914D;">Exponential (in-place)</b> → <code>torch.exp_()</code></li>
    <li><b style="color:#FF914D;">Square Root (in-place)</b> → <code>torch.sqrt_()</code></li>
    <li><b style="color:#FF914D;">Logarithm (in-place)</b> → <code>torch.log_()</code></li>
    <li><b style="color:#FF914D;">Power (in-place)</b> → <code>torch.pow_()</code></li>
    <li><b style="color:#FF914D;">Tanh (in-place)</b> → <code>torch.tanh_()</code></li>
    <li><b style="color:#FF914D;">Absolute Value (in-place)</b> → <code>torch.abs_()</code></li>
</ul>

<h2 style="color:#33A1FF; font-size:25px;">🔟 Reshaping Tensors in PyTorch</h2>
<ul style="font-size:18px;">
    <li><b style="color:#FF914D;">Reshaping a tensor</b> → <code>torch.view()</code>, <code>tensor.reshape()</code></li>
    <li><b style="color:#FF914D;">Flattening a tensor</b> → <code>tensor.flatten()</code></li>
    <li><b style="color:#FF914D;">Changing the dimensions</b> → <code>torch.unsqueeze()</code>, <code>torch.squeeze()</code></li>
    <li><b style="color:#FF914D;">Permuting dimensions</b> → <code>torch.permute()</code></li>
</ul>

<h2 style="color:#33A1FF; font-size:25px;">1️⃣1️⃣ NumPy and PyTorch</h2>
<ul style="font-size:18px;">
    <li><b style="color:#FF914D;">Conversion from NumPy to PyTorch tensor</b> → <code>torch.from_numpy()</code></li>
    <li><b style="color:#FF914D;">Conversion from PyTorch tensor to NumPy</b> → <code>tensor.numpy()</code></li>
    <li><b style="color:#FF914D;">NumPy-style operations in PyTorch</b> → PyTorch supports similar functions as NumPy for array manipulation and mathematical operations.
</ul>


<h2 style="color:#33A1FF; font-size:25px;">Basic Arithmetic Operations</h2>


In [48]:
# Create a  Tensor
t1  = torch.rand(3,3)

In [49]:
t1

tensor([[0.6502, 0.4691, 0.6590],
        [0.2622, 0.2572, 0.2135],
        [0.8800, 0.2727, 0.8929]])

In [50]:
# Addition
t1 + 4

tensor([[4.6502, 4.4691, 4.6590],
        [4.2622, 4.2572, 4.2135],
        [4.8800, 4.2727, 4.8929]])

In [51]:
# Subtaction
t1 - 2

tensor([[-1.3498, -1.5309, -1.3410],
        [-1.7378, -1.7428, -1.7865],
        [-1.1200, -1.7273, -1.1071]])

In [52]:
# Multiplication
t1 * 3

tensor([[1.9506, 1.4074, 1.9770],
        [0.7866, 0.7716, 0.6406],
        [2.6401, 0.8182, 2.6787]])

In [53]:
# Devision
t1 / 2

tensor([[0.3251, 0.2346, 0.3295],
        [0.1311, 0.1286, 0.1068],
        [0.4400, 0.1364, 0.4464]])

In [54]:
# modulos
((t1 * 100)/4)%2

tensor([[2.5487e-01, 1.7280e+00, 4.7496e-01],
        [5.5489e-01, 4.3024e-01, 1.3385e+00],
        [8.9836e-04, 8.1870e-01, 3.2217e-01]])

In [55]:
# power
t1**2

tensor([[0.4228, 0.2201, 0.4343],
        [0.0687, 0.0662, 0.0456],
        [0.7745, 0.0744, 0.7972]])

<h2 style="color:#33A1FF; font-size:25px;">Element wise oparation</h2>


In [ ]:
a = torch.rand(2,2)
b = torch.rand(2,2)

In [58]:
print(a)
print(b)

tensor([[0.9974, 0.5021],
        [0.5220, 0.1304]])
tensor([[0.8244, 0.4092],
        [0.8941, 0.2680]])


In [59]:
# Additon 
a + b

tensor([[1.8218, 0.9113],
        [1.4161, 0.3984]])

In [60]:
# Subtraction 
a - b

tensor([[ 0.1731,  0.0929],
        [-0.3721, -0.1375]])

In [61]:
# Multiplication 
a * b

tensor([[0.8222, 0.2055],
        [0.4667, 0.0350]])

In [63]:
# Devision 
b/a

tensor([[0.8265, 0.8151],
        [1.7129, 2.0542]])

In [64]:
# Modules
a % b

tensor([[0.1731, 0.0929],
        [0.5220, 0.1304]])

In [65]:
# power
b**a

tensor([[0.8248, 0.6385],
        [0.9432, 0.8422]])

In [69]:
t2 = torch.tensor([-1,2,3,-4,-5])
t2

tensor([-1,  2,  3, -4, -5])

In [70]:
# Absalute
torch.abs(t2)

tensor([1, 2, 3, 4, 5])

In [72]:
t3 = torch.tensor([3.5,2.1,3.89,8.93,5.5])
t3

tensor([3.5000, 2.1000, 3.8900, 8.9300, 5.5000])

In [73]:
# round 
torch.round(t3)

tensor([4., 2., 4., 9., 6.])

In [74]:
# ceil
torch.ceil(t3)

tensor([4., 3., 4., 9., 6.])

In [75]:
# floor
torch.floor(t3)

tensor([3., 2., 3., 8., 5.])

In [76]:
# clamp
torch.clamp(t3, min=1, max=4)

tensor([3.5000, 2.1000, 3.8900, 4.0000, 4.0000])

<h2 style="color:#33A1FF; font-size:25px;">Reduction  Oparation</h2>

In [100]:
t4 = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
t4

tensor([[4., 6., 1.],
        [7., 4., 6.],
        [7., 1., 3.]])

In [101]:
# sum()
torch.sum(t4)

tensor(39.)

In [102]:
# sum along column
torch.sum(t4, dim=0)

tensor([18., 11., 10.])

In [103]:
# sum along rows
torch.sum(t4, dim=1)

tensor([11., 17., 11.])

In [104]:
# mean()
torch.mean(t4)

tensor(4.3333)

In [105]:
# mean along column
torch.mean(t4, dim=0)

tensor([6.0000, 3.6667, 3.3333])

In [106]:
# median 
torch.median(t4)

tensor(4.)

In [107]:
# max()
torch.max(t4)

tensor(7.)

In [113]:
# produc
torch.prod(t4)

tensor(84672.)

In [114]:
# Standard Daviation
torch.std(t4)

tensor(2.3452)

<h2 style="color:#33A1FF; font-size:25px;">Matrix Operations</h2>


In [115]:
t5 = torch.randint(size=(2,3), low=1, high=10)
t6 = torch.randint(size=(3,2), low=1, high=10)

In [116]:
print(t5)
print(t6)

tensor([[1, 6, 5],
        [6, 9, 9]])
tensor([[7, 3],
        [4, 3],
        [8, 6]])


In [118]:
# Matric Maltiplication
torch.matmul(t5,t6)

tensor([[ 71,  51],
        [150,  99]])

In [122]:
v1  = torch.tensor([1,2,3])
v2 = torch.tensor([4,5,6])
print(v1)
print(v2)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [123]:
# Dot product
torch.dot(v1,v2)

tensor(32)

In [127]:
# Transpose 
torch.transpose(t6, 1,0)

tensor([[7, 4, 8],
        [3, 3, 6]])

In [138]:
# Determinat 
t7 = torch.randint(size=(3,3), low=1, high=10, dtype = torch.float32)
print(t7)
torch.det(t7)

tensor([[6., 3., 8.],
        [5., 1., 6.],
        [7., 1., 4.]])


tensor(38.)

In [140]:
# Inverse
torch.inverse(t7)

tensor([[-0.0526, -0.1053,  0.2632],
        [ 0.5789, -0.8421,  0.1053],
        [-0.0526,  0.3947, -0.2368]])

<h2 style="color:#33A1FF; font-size:25px;">Comparsion Oparation</h2>


In [142]:
t8 = torch.randint(size=(3,2), low=1, high=10)
t9 = torch.randint(size=(3,2), low=1, high=10)
print(t8)
print(t9)

tensor([[3, 9],
        [9, 6],
        [3, 7]])
tensor([[7, 1],
        [4, 2],
        [6, 8]])


In [143]:
# Greater then
t8 > t9

tensor([[False,  True],
        [ True,  True],
        [False, False]])

In [144]:
# less then and equal to 
t8 <= t9

tensor([[ True, False],
        [False, False],
        [ True,  True]])

In [145]:
# Not equal to 
t9 != t8

tensor([[True, True],
        [True, True],
        [True, True]])

<h2 style="color:#33A1FF; font-size:25px;">Special Functions</h2>


In [147]:
a = torch.randint(size=(3,4), low=1, high=10)

In [148]:
# Log
torch.log(a)

tensor([[1.7918, 0.0000, 1.7918, 2.0794],
        [1.7918, 0.6931, 1.9459, 1.0986],
        [1.6094, 1.7918, 1.7918, 0.0000]])

In [149]:
# Square Root
torch.sqrt(a)

tensor([[2.4495, 1.0000, 2.4495, 2.8284],
        [2.4495, 1.4142, 2.6458, 1.7321],
        [2.2361, 2.4495, 2.4495, 1.0000]])

In [150]:
# Exponantial 
torch.exp(a)

tensor([[4.0343e+02, 2.7183e+00, 4.0343e+02, 2.9810e+03],
        [4.0343e+02, 7.3891e+00, 1.0966e+03, 2.0086e+01],
        [1.4841e+02, 4.0343e+02, 4.0343e+02, 2.7183e+00]])

In [151]:
# Sigmoid
torch.sigmoid(a)

tensor([[0.9975, 0.7311, 0.9975, 0.9997],
        [0.9975, 0.8808, 0.9991, 0.9526],
        [0.9933, 0.9975, 0.9975, 0.7311]])

In [155]:
b = torch.randint(size=(3,4), low=1, high=10, dtype = torch.float64)

In [157]:
# Softmax 
torch.softmax(b, dim=1)

tensor([[3.3422e-04, 9.9629e-01, 9.0850e-04, 2.4696e-03],
        [9.5092e-01, 8.6713e-04, 4.7344e-02, 8.6713e-04],
        [4.3317e-02, 4.3317e-02, 4.3317e-02, 8.7005e-01]], dtype=torch.float64)

In [158]:
# relu 
torch.relu(a)

tensor([[6, 1, 6, 8],
        [6, 2, 7, 3],
        [5, 6, 6, 1]])

<h2 style="color:#33A1FF; font-size:25px;">Inplace Functions</h2>

In [160]:
c = torch.randint(size=(3,3), low=1, high=10)
c

tensor([[1, 4, 6],
        [1, 3, 1],
        [5, 5, 8]])

In [163]:
# to keep the changes permanetly, put underscore ( _ ) after the function
c.relu_()
print(c)

tensor([[1, 4, 6],
        [1, 3, 1],
        [5, 5, 8]])


<h2 style="color:#33A1FF; font-size:25px;">Copying a Tensor</h2>


In [164]:
d = torch.randint(size=(2,3), low=1, high=10)
d

tensor([[9, 6, 3],
        [8, 1, 1]])

In [167]:
# By Assigment Oparator
e = d

In [168]:
e

tensor([[9, 6, 3],
        [8, 1, 1]])

In [169]:
d

tensor([[9, 6, 3],
        [8, 1, 1]])

In [170]:
d[1][2] = 4

In [171]:
d

tensor([[9, 6, 3],
        [8, 1, 4]])

In [172]:
# using of clone()
e = d.clone()

In [175]:
print(e)

print(d)

tensor([[9, 6, 3],
        [8, 1, 4]])
tensor([[9, 6, 3],
        [8, 1, 4]])


In [176]:
# both the tensor are same d and e to see
print(id(d))
print(id(e))

2311815248640
2311737397056


In [179]:
torch.cuda.is_available()

False

<h2 style="color:#33A1FF; font-size:25px;">Reshaping a Tensor</h2>

In [197]:
f = torch.ones(4,4)
f

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [198]:
# reshape
f.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [199]:
# Flatten 
f.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [214]:
#  permute
g = torch.rand(3,2,3)
print(g)
g.permute(2,0,1).shape

tensor([[[0.7895, 0.2164, 0.9363],
         [0.8914, 0.3771, 0.6164]],

        [[0.7408, 0.0844, 0.0827],
         [0.0084, 0.7022, 0.0943]],

        [[0.5728, 0.0439, 0.9115],
         [0.9218, 0.0532, 0.9605]]])


torch.Size([3, 3, 2])

In [220]:
# unsqueeze 
h = torch.rand(226,226,3)
h.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [226]:
k = torch.rand(1,3)
k.squeeze(0).shape

torch.Size([3])

<h2 style="color:#33A1FF; font-size:25px;">Numpy Vs PyTorch</h2>


In [228]:
# Torch to Nmupy Array
import numpy as np
m = torch.tensor([1,2,3])
m

tensor([1, 2, 3])

In [229]:
n = m.numpy()

In [231]:
type(n)

numpy.ndarray

In [234]:
# numpy to PyTorch 
p = np.array([1,2,3])
p

array([1, 2, 3])

In [233]:
torch.from_numpy(p)

tensor([1, 2, 3])