<h1 style="color:#ff5733; text-align:center; font-size:45px;">🚀 Hello! I'm <b style="color:#33A1FF;">Yahya Ahmad</b> 👋</h1>

<p style="font-size:22px; text-align:center; color:#444;">
I'm a beginner passionate about <b style="color:#FF914D;">technology</b>, <b style="color:#FF914D;">machine learning</b>, and <b style="color:#FF914D;">Python programming</b>. 
I'm excited to learn and grow in the world of <b style="color:#33A1FF;">data science</b> and <b style="color:#33A1FF;">AI</b>. 🚀
</p>

<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#33A1FF; font-size:30px;">🎯 My Interests:</h2>

<ul style="font-size:22px; color:#444;">
    <li><b style="color:#FF914D;">Programming</b>: Python </li>
    <li><b style="color:#FF914D;">Machine Learning</b>: Exploring PyTorch and TensorFlow</li>
    <li><b style="color:#FF914D;">Deep Learning AI</b>: Neural Networks & Computer Vision</li>
</ul>

<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#33A1FF; font-size:30px;">📬 Let's Connect!</h2>

<ul style="font-size:22px; color:#444;">
    <li>📧 <b>Email</b>: <a href="mailto:Ya0280780@gmail.com" style="color:#FF914D;">Ya0280780@gmail.com</a></li>
    <li>🔗 <b>LinkedIn</b>: <a href="https://www.linkedin.com/in/yahya-ahmad-8538312b1/" style="color:#FF914D;">Yahya Ahmad on LinkedIn</a></li>
    <li>💻 <b>GitHub</b>: <a href="https://github.com/Yahyaahmad09/Courses" style="color:#FF914D;">My GitHub Repository</a></li>
</ul>

<hr style="border:2px solid #ff5733; width:80%;">


<h1 style="color:#ff5733; text-align:center; font-size:35px;">🔄 AutoGrad in PyTorch</h1>

<hr style="border:2px solid #ff5733;">

<p style="font-size:18px;">
PyTorch's <b style="color:#33A1FF;">Autograd</b> (Automatic Differentiation) is a core feature that enables dynamic computation of gradients. It allows for automatic differentiation of tensors with respect to other tensors, which is crucial for deep learning models and optimization tasks.
</p>

<h2 style="color:#33A1FF; font-size:25px;">✅ Key Features of Autograd</h2>
<ul style="font-size:18px;">
    <li><b style="color:#FF914D;">Computational Graph:</b> Tracks operations on tensors dynamically.</li>
    <li><b style="color:#FF914D;">Gradient Calculation:</b> Computes gradients automatically using <code>backward()</code>.</li>
    <li><b style="color:#FF914D;">Optimized for Deep Learning:</b> Efficiently computes derivatives needed for training neural networks.</li>
</ul>

<h2 style="color:#33A1FF; font-size:25px;">⚙️ How Autograd Works</h2>
<p style="font-size:18px;">
Autograd creates a dynamic computational graph for each tensor operation, storing gradients in <code>tensor.grad</code>. The <code>requires_grad=True</code> flag enables gradient tracking, and calling <code>tensor.backward()</code> computes the derivatives.
</p>

<h2 style="color:#33A1FF; font-size:25px;">📝 Example Usage</h2>

```python
import torch

# Create tensors with gradient tracking
x = torch.tensor(2.0, requires_grad=True)
y = x ** 3  # y = x^3

# Compute gradient
y.backward()

# Print the gradient dy/dx
print(x.grad)  # Output: 12.0 (since dy/dx = 3x^2 = 3*(2^2) = 12)


<h2 style="color:#3498db; font-size:30px;">🔑 Code to Import PyTorch and Other Libraries</h2>


In [69]:
import torch
import math

<h2 style="color:#3498db; font-size:30px;">AutoGrad Implimentation</h2>

In [70]:
# create a tenser 
x = torch.tensor(3.0, requires_grad=True)
x

tensor(3., requires_grad=True)

In [71]:
y = x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [72]:
# using Backword
y.backward()

In [73]:
# using Grad for Gradiant
print(x.grad)

tensor(6.)


In [74]:
# Define a function
def dz_dx(x):   # dz/dx in simple way
    return 2 * x * math.cos(y)

In [75]:
dz_dx(2.3)

-4.1911992046695135

In [76]:
# using AutoGrad in pytorch 
x = torch.tensor(2.3, requires_grad=True)
x

tensor(2.3000, requires_grad=True)

In [77]:
y = x**2
y

tensor(5.2900, grad_fn=<PowBackward0>)

In [78]:
z = torch.sin(y)
z

tensor(-0.8378, grad_fn=<SinBackward0>)

In [79]:
# backword prop
z.backward()   # using chain rule

In [80]:
# using grad
x.grad

tensor(2.5117)

<h1 style="color:#ff5733; text-align:center; font-size:35px;">Simple NN Example</h1>
<h1 style="color:#ff5733; text-align:center; font-size:30px;">Using Manual Method</h1>

<h2 style="color:#3498db; font-size:30px;">Inputs</h2>


In [84]:
# Example of simple NN
# input 
x = torch.tensor(6.7)  # Input feature
y = torch.tensor(0.0)  # True Lable (Binary)

w = torch.tensor(1.0) # weight
b = torch.tensor(0.0) # bias

print('X: ', x)
print('Y: ', y)
print('W: ', w)
print('b: ', b)

X:  tensor(6.7000)
Y:  tensor(0.)
W:  tensor(1.)
b:  tensor(0.)


<h2 style="color:#3498db; font-size:30px;">Function for Losses</h2>

In [85]:
# Binary cross Entropy loss for scalar 
def Binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8 # for log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

<h2 style="color:#3498db; font-size:30px;">Forward Pass</h2>

In [90]:
# forward Pass
z = w * x + b  # linear Combination
y_pred = torch.sigmoid(z)  # Apply Activation Function

# compute Binary_cross_entropy_loss (Losses)
loss = Binary_cross_entropy_loss(y_pred,y)
print(loss)

tensor(6.7012)


<h2 style="color:#3498db; font-size:30px;">Backward Pass </h2>

In [96]:
# Manul style Derivatives
# 1:- dL/dy_pred: Loss w.r.t Prediction
dL_dy_pred = (y_pred - y) /(y_pred*(1-y_pred))

# 2:- dy_pred/dz: y_pred w.r.t z (Activation function)
dy_pred_dz = y_pred * (1-y_pred)

# 2:- dz/dw: Activation  w.r.t weight(w),  dz/db: Activation  w.r.t bias  
dz_dw = x 
dz_db = 1

dL_dw = dL_dy_pred * dy_pred_dz * dz_dw
dL_db = dL_dy_pred * dy_pred_dz * dz_db

# Print the Gradient loss
print('Manual Gradient loss w.r.t W: ', dL_dw)
print('Manual Gradient loss w.r.t b: ', dL_db)

Manual Gradient loss w.r.t W:  tensor(6.6918)
Manual Gradient loss w.r.t b:  tensor(0.9988)


<h1 style="color:#ff5733; text-align:center; font-size:35px;">Using AutoGrad</h1>


<h2 style="color:#3498db; font-size:30px;">Inputs</h2>


In [98]:
x = torch.tensor(6.7)  # input feature
y = torch.tensor(0.0) # True labels
print(x)
print(y)

tensor(6.7000)
tensor(0.)


In [101]:
w = torch.tensor(1.0, requires_grad=True) # w as weight
b = torch.tensor(0.0, requires_grad=True) # b as bais
print(w)
print(b)

tensor(1., requires_grad=True)
tensor(0., requires_grad=True)


<h1 style="color:#ff5733; text-align:center; font-size:35px;">Forward Pass</h1>


<h2 style="color:#3498db; font-size:30px;">Linear Combination</h2>


In [104]:
z = w*x+b  # linear combination for z
z

tensor(6.7000, grad_fn=<AddBackward0>)

<h2 style="color:#3498db; font-size:30px;">Activation Function</h2>


In [106]:
y_pred = torch.sigmoid(z) # Sigmoid function on z as Activation function
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

<h2 style="color:#3498db; font-size:30px;">Loss Function</h2>


In [110]:
# Binary cross Entropy loss for scalar 
def Binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8 # for log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

<h2 style="color:#3498db; font-size:30px;">Losses</h2>


In [112]:
loss = Binary_cross_entropy_loss(y_pred, y) # Losses between prediction and target value
loss 

tensor(6.7012, grad_fn=<NegBackward0>)

<h1 style="color:#ff5733; text-align:center; font-size:35px;">Backward Pass</h1>

In [113]:
# using backward 
loss.backward()  # compute Gradient

In [115]:
print(w.grad)   # store in grad for w
print(b.grad)   # store in grad for b

tensor(6.6918)
tensor(0.9988)


<h1 style="color:#ff5733; text-align:center; font-size:35px;">Auto Grad on Vector</h1>

In [135]:
# input feature
x = torch.tensor([2.5, 4.2, 7.8], requires_grad=True)
x

tensor([2.5000, 4.2000, 7.8000], requires_grad=True)

In [136]:
# forward pass
y = (x**2).mean()
y

tensor(28.2433, grad_fn=<MeanBackward0>)

In [137]:
# Backward pass
y.backward()

In [138]:
# Gradient
x.grad

tensor([1.6667, 2.8000, 5.2000])

In [140]:
# clear Gradient
x.grad.zero_() # use to clear the gradient after backward if we want to  keep the gradient value unchange 
               # (because after each run of passess the grad change)

tensor([0., 0., 0.])

In [142]:
# Disable Gradient Trackinga
x = torch.tensor(2.0, requires_grad = True)
x

tensor(2., requires_grad=True)

In [144]:
y = x**3
y

tensor(8., grad_fn=<PowBackward0>)

In [145]:
y.backward()

In [146]:
x.grad

tensor(12.)

In [149]:
# using requires_gradient(False)
x.requires_grad_(False)

tensor(2.)

In [150]:
# using detach()
x.detach()

tensor(2.)

In [151]:
# using torch.no_grad()
torch.no_grad(x)

<function torch.context_decorator.<locals>.decorate_context>