<h1 style="color:#ff5733; text-align:center; font-size:45px;">🚀 Hello! I'm <b style="color:#33A1FF;">Yahya Ahmad</b> 👋</h1>

<p style="font-size:22px; text-align:center; color:#444;">
I'm a beginner passionate about <b style="color:#FF914D;">technology</b>, <b style="color:#FF914D;">machine learning</b>, and <b style="color:#FF914D;">Python programming</b>. 
I'm excited to learn and grow in the world of <b style="color:#33A1FF;">data science</b> and <b style="color:#33A1FF;">AI</b>. 🚀
</p>

<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#33A1FF; font-size:30px;">🎯 My Interests:</h2>

<ul style="font-size:22px; color:#444;">
    <li><b style="color:#FF914D;">Programming</b>: Python </li>
    <li><b style="color:#FF914D;">Machine Learning</b>: Exploring PyTorch and TensorFlow</li>
    <li><b style="color:#FF914D;">Deep Learning AI</b>: Neural Networks & Computer Vision</li>
</ul>

<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#33A1FF; font-size:30px;">📬 Let's Connect!</h2>

<ul style="font-size:22px; color:#444;">
    <li>📧 <b>Email</b>: <a href="mailto:Ya0280780@gmail.com" style="color:#FF914D;">Ya0280780@gmail.com</a></li>
    <li>🔗 <b>LinkedIn</b>: <a href="https://www.linkedin.com/in/yahya-ahmad-8538312b1/" style="color:#FF914D;">Yahya Ahmad on LinkedIn</a></li>
    <li>💻 <b>GitHub</b>: <a href="https://github.com/Yahyaahmad09/Courses" style="color:#FF914D;">My GitHub Repository</a></li>
</ul>

<hr style="border:2px solid #ff5733; width:80%;">


<h1 style="color:#ff5733; text-align:center; font-size:35px;">🔥 Understanding PyTorch <b style="color:#33A1FF;">NN Module</b> 🚀</h1>

<hr style="border:2px solid #ff5733; width:80%;">

<p style="font-size:18px; text-align:center; color:#444;">
    The <b style="color:#FF914D;">torch.nn</b> module in PyTorch provides an easy way to build, train, and deploy <b style="color:#33A1FF;">deep learning models</b>. 
    It simplifies the process of defining layers, activation functions, and backpropagation. Let's explore its powerful features! ⚡
</p>

<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#33A1FF; font-size:22px;">🔹 1. What is the PyTorch NN Module?</h2>
<p style="font-size:22px; color:#444;">The <b style="color:#FF914D;">torch.nn</b> module provides pre-built layers and loss functions, making it easy to define **Neural Networks**.</p>

<h2 style="color:#33A1FF; font-size:22px;">🔹 2. Key Components of torch.nn</h2>
<ul style="font-size:18px; color:#444;">
    <li><b style="color:#FF914D;">Neural Network Layers</b>: Linear, Convolutional, Recurrent, etc.</li>
    <li><b style="color:#FF914D;">Activation Functions</b>: ReLU, Sigmoid, Softmax, etc.</li>
    <li><b style="color:#FF914D;">Loss Functions</b>: MSE Loss, Cross-Entropy Loss, etc.</li>
    <li><b style="color:#FF914D;">Optimizers</b>: Adam, SGD, RMSprop, etc.</li>
</ul>

<h2 style="color:#33A1FF; font-size:22px;">🔹 3. Building a Model with torch.nn</h2>
<p style="font-size:18px; color:#444;">
    PyTorch allows defining models using **nn.Module**, making it easier to create custom architectures with forward propagation. 🔥
</p>

<h2 style="color:#33A1FF; font-size:22px;">🔹 4. Training a Neural Network</h2>
<p style="font-size:18px; color:#444;">The training process includes:</p>
<ul style="font-size:22px; color:#444;">
    <li>Forward Pass 🚀</li>
    <li>Loss Calculation 📉</li>
    <li>Backward Propagation 🔄</li>
    <li>Weight Updates ✨</li>
</ul>

<h2 style="color:#33A1FF; font-size:22px;">🔹 5. Model Evaluation</h2>
<p style="font-size:18px; color:#444;">
    Evaluate the model using accuracy, loss, and visualization techniques to check its performance. 📊
</p>

<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#33A1FF; font-size:25px;">💡 Ready to Dive into PyTorch NN Module?</h2>
<p style="font-size:18px; color:#444; text-align:center;">
    Let's build and train amazing deep learning models using <b style="color:#FF914D;">PyTorch NN Module</b>! 🚀🔥
</p>

<hr style="border:2px solid #ff5733; width:80%;">


<h1 style="color:#ff5733; text-align:center; font-size:35px;">🔥 Single Layer Neural Network 🚀</h1>


<h2 style="color:#3498db; font-size:30px;">🔑 Code to Import PyTorch and Other Libraries</h2>


In [2]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)  # create a fully connected layer 
        self.sigmoid = nn.Sigmoid()  # Converts raw output into values between 0 and 1.

    def forward(self, features):
        z = self.linear(features)  
        y_pred = self.sigmoid(z)  
        return y_pred

In [5]:
# create dataset
features = torch.rand(10,5)

In [6]:
# create object of model 
model = Model(features.shape[1])

In [7]:
# call model for forward pass
model(features)

tensor([[0.6232],
        [0.6186],
        [0.6166],
        [0.6234],
        [0.6206],
        [0.6145],
        [0.6280],
        [0.6252],
        [0.6276],
        [0.6179]], grad_fn=<SigmoidBackward0>)

In [8]:
# show the weights or bias of the layer (linear)
model.linear.weight

Parameter containing:
tensor([[0.0898, 0.0501, 0.0705, 0.0944, 0.0248]], requires_grad=True)

In [9]:
from torchinfo import summary

In [10]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

<h1 style="color:#ff5733; text-align:center; font-size:35px;">🔥 Three layer Neural Network 🚀</h1>


In [11]:
class Model(nn.Module):
    def __init__(self, num_features):
    # use a manual methed 
        """super().__init__()
        self.linear1  = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        z = self.linear1(features)
        y_pred = self.relu(z)
        z = self.linear2(features)
        y_pred = self.sigmoid(z)
        return y_pred"""
    # use a sequential module of NN
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        y_pred = self.network(features)
        return y_pred

In [12]:
# create a dataset
features = torch.rand(10,5)

In [13]:
# create object of model
model = Model(features.shape[1])

In [14]:
# call the model for forward
model(features)

tensor([[0.5766],
        [0.5337],
        [0.5571],
        [0.5159],
        [0.5202],
        [0.5107],
        [0.5158],
        [0.5433],
        [0.5201],
        [0.5459]], grad_fn=<SigmoidBackward0>)

In [15]:
# show the weights and bias 


In [16]:
# show the summary 
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

<h1 style="color:#ff5733; text-align:center; font-size:35px;">🔥 Code Example of Breast Cancer DataSet🚀</h1>


In [3]:
# Already import labraries
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/master/data.csv")

In [4]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id','Unnamed: 32'], inplace = True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:, 1:] , df.iloc[:, 0], test_size=0.2)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-0.5370467 ,  1.70408785, -0.47563683, ...,  0.43732559,
         0.4852181 ,  2.04534613],
       [ 0.0036438 ,  0.71949071,  0.03665086, ...,  0.2889283 ,
        -0.32108509, -0.03428394],
       [-0.1588435 , -0.76083169, -0.20406752, ..., -0.72583379,
         0.65365281, -0.39972313],
       ...,
       [-0.15604199, -0.40217333, -0.20731499, ..., -0.40609118,
        -0.60180961, -0.8163238 ],
       [ 1.17467297,  0.57328603,  1.1095323 , ...,  0.31493607,
         0.31990255, -0.45088461],
       [-1.26123579,  2.01020391, -1.26598877, ..., -1.05031901,
        -0.909047  , -0.67520805]], shape=(455, 30))

In [9]:
# Encode the data to (0,1)
encoder = LabelEncoder()
Y_train = encoder.fit_transform(Y_train)
Y_test = encoder.transform(Y_test)
Y_train

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,

In [10]:
X_test_tensor = torch.from_numpy(X_test).float()
X_train_tensor = torch.from_numpy(X_train).float()
Y_test_tensor = torch.from_numpy(Y_test).float()
Y_train_tensor = torch.from_numpy(Y_train).float()

In [70]:
X_train_tensor.shape

torch.Size([455, 30])

In [71]:
Y_train_tensor.shape

torch.Size([455])

<h1 style="color:#ff5733; text-align:center; font-size:35px;">🔥 <b style="color:#33A1FF;">Main NN Module</b> 🚀</h1>


In [72]:
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super(MySimpleNN, self).__init__()
        self.linear = nn.Linear(num_features, 1)  # Linear layer
        self.sigmoid = nn.Sigmoid()  # Sigmoid activation

    def forward(self, features):
        z = self.linear(features)  # Linear transformation
        y_pred = self.sigmoid(z)  # Apply sigmoid
        return y_pred

    def loss_function(self, y_pred, y):
        # clamp prediction to aovid log(0)
        epsilon = 1e-8
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        #calculate loss
        loss = -(Y_train_tensor * torch.log(y_pred) + (1 - Y_train_tensor) * torch.log(1 -y_pred)).mean()
        return loss

In [73]:
# Important Parameters
learning_rate = 0.01
epochs = 25

In [74]:
# Training Pipline 
# create model
model = MySimpleNN(X_train_tensor.shape[1])
# define loopabs
for epoch in range(epochs):
    # forward pass 
    y_pred = model(X_train_tensor)
    # loss function
    loss = model.loss_function(y_pred,Y_train_tensor)
    # Backward Pass 
    loss.backward()
    # Update Parameters
    with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad
    # zero gradient
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    print(f'Epoch: {epoch + 1}, Loss:{loss.item()} ')

Epoch: 1, Loss:0.7369337677955627 
Epoch: 2, Loss:0.7347106337547302 
Epoch: 3, Loss:0.7325944900512695 
Epoch: 4, Loss:0.7305803298950195 
Epoch: 5, Loss:0.7286635041236877 
Epoch: 6, Loss:0.7268393039703369 
Epoch: 7, Loss:0.7251032590866089 
Epoch: 8, Loss:0.7234512567520142 
Epoch: 9, Loss:0.7218789458274841 
Epoch: 10, Loss:0.7203823328018188 
Epoch: 11, Loss:0.7189577221870422 
Epoch: 12, Loss:0.7176014184951782 
Epoch: 13, Loss:0.7163099050521851 
Epoch: 14, Loss:0.7150798439979553 
Epoch: 15, Loss:0.7139080166816711 
Epoch: 16, Loss:0.712791383266449 
Epoch: 17, Loss:0.7117270827293396 
Epoch: 18, Loss:0.7107123136520386 
Epoch: 19, Loss:0.7097444534301758 
Epoch: 20, Loss:0.7088209986686707 
Epoch: 21, Loss:0.7079395651817322 
Epoch: 22, Loss:0.7070980072021484 
Epoch: 23, Loss:0.706294059753418 
Epoch: 24, Loss:0.7055257558822632 
Epoch: 25, Loss:0.7047911882400513 


In [75]:
# Model Evaluatio
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == Y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')
 

Accuracy: 0.5775623321533203


### Use nn  module function 

In [63]:
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super(MySimpleNN, self).__init__()
        self.linear = nn.Linear(num_features, 1)  # Linear layer
        self.sigmoid = nn.Sigmoid()  # Sigmoid activation

    def forward(self, features):
        z = self.linear(features)  # Linear transformation
        y_pred = self.sigmoid(z)  # Apply sigmoid
        return y_pred



In [76]:
learning_rate = 0.01
epochs = 25

In [81]:
# Binary cross entropy loss function
Loss = nn.BCELoss()

In [84]:
# use optimazer 
optimazwer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [88]:
# Training Pipline 
# create model
model = MySimpleNN(X_train_tensor.shape[1])
# define loopabs
for epoch in range(epochs):
    # forward pass 
    y_pred = model(X_train_tensor)
    # loss function
    loss = Loss(y_pred,Y_train_tensor.view(-1,1))
    # Backward Pass 
    loss.backward()
    # Update Parameters
    """ with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad"""
    optimazwer.step()

    optimazwer.zero_grad()
    
    print(f'Epoch: {epoch + 1}, Loss:{loss.item()} ')

Epoch: 1, Loss:0.44549915194511414 
Epoch: 2, Loss:0.44549915194511414 
Epoch: 3, Loss:0.44549915194511414 
Epoch: 4, Loss:0.44549915194511414 
Epoch: 5, Loss:0.44549915194511414 
Epoch: 6, Loss:0.44549915194511414 
Epoch: 7, Loss:0.44549915194511414 
Epoch: 8, Loss:0.44549915194511414 
Epoch: 9, Loss:0.44549915194511414 
Epoch: 10, Loss:0.44549915194511414 
Epoch: 11, Loss:0.44549915194511414 
Epoch: 12, Loss:0.44549915194511414 
Epoch: 13, Loss:0.44549915194511414 
Epoch: 14, Loss:0.44549915194511414 
Epoch: 15, Loss:0.44549915194511414 
Epoch: 16, Loss:0.44549915194511414 
Epoch: 17, Loss:0.44549915194511414 
Epoch: 18, Loss:0.44549915194511414 
Epoch: 19, Loss:0.44549915194511414 
Epoch: 20, Loss:0.44549915194511414 
Epoch: 21, Loss:0.44549915194511414 
Epoch: 22, Loss:0.44549915194511414 
Epoch: 23, Loss:0.44549915194511414 
Epoch: 24, Loss:0.44549915194511414 
Epoch: 25, Loss:0.44549915194511414 


In [89]:
# Model Evaluatio
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == Y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')
 

Accuracy: 0.5083102583885193
