<h1 style="color:#ff5733; text-align:center; font-size:45px;">🚀 Hello! I'm <b style="color:#33A1FF;">Yahya Ahmad</b> 👋</h1>

<p style="font-size:22px; text-align:center; color:#444;">
I'm a beginner passionate about <b style="color:#FF914D;">technology</b>, <b style="color:#FF914D;">machine learning</b>, and <b style="color:#FF914D;">Python programming</b>. 
I'm excited to learn and grow in the world of <b style="color:#33A1FF;">data science</b> and <b style="color:#33A1FF;">AI</b>. 🚀
</p>

<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#33A1FF; font-size:30px;">🎯 My Interests:</h2>

<ul style="font-size:22px; color:#444;">
    <li><b style="color:#FF914D;">Programming</b>: Python </li>
    <li><b style="color:#FF914D;">Machine Learning</b>: Exploring PyTorch and TensorFlow</li>
    <li><b style="color:#FF914D;">Deep Learning AI</b>: Neural Networks & Computer Vision</li>
</ul>

<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#33A1FF; font-size:30px;">📬 Let's Connect!</h2>

<ul style="font-size:22px; color:#444;">
    <li>📧 <b>Email</b>: <a href="mailto:Ya0280780@gmail.com" style="color:#FF914D;">Ya0280780@gmail.com</a></li>
    <li>🔗 <b>LinkedIn</b>: <a href="https://www.linkedin.com/in/yahya-ahmad-8538312b1/" style="color:#FF914D;">Yahya Ahmad on LinkedIn</a></li>
    <li>💻 <b>GitHub</b>: <a href="https://github.com/Yahyaahmad09/Courses" style="color:#FF914D;">My GitHub Repository</a></li>
</ul>

<hr style="border:2px solid #ff5733; width:80%;">


<h1 style="color:#ff6600;">📌 Dataset and DataLoader in PyTorch</h1>

<h2 style="color:#3366cc;">1️⃣ What is a Dataset class?</h2>
<p>
A <b>Dataset</b> in PyTorch is a class that helps load and preprocess data. It is usually created by subclassing <code>torch.utils.data.Dataset</code> and defining <code>__len__</code> and <code>__getitem__</code> methods.
</p>

<h2 style="color:#3366cc;">2️⃣ What is a DataLoader class?</h2>
<p>
The <b>DataLoader</b> in PyTorch helps in efficient data loading by handling <i>batching, shuffling, and multiprocessing</i>. It works with any dataset that follows the <code>Dataset</code> class structure.
</p>

<h2 style="color:#ff6600;">✅ Key Benefits</h2>
<ul>
    <li><b>Efficient Data Loading:</b> Handles large datasets by loading them in small batches.</li>
    <li><b>Shuffling:</b> Randomizes data order to improve training.</li>
    <li><b>Parallel Processing:</b> Uses multiple workers for faster data loading.</li>
</ul>

<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#3366cc;">📌 Import the Necessary Libraries</h2>
<p>Before we begin, let's import the required libraries for working with datasets and dataloaders in PyTorch.</p>

<h2 style="color:#ff6600;">🔹 Convert the Data into PyTorch Tensors</h2>
<p>We need to convert our data into PyTorch tensors for compatibility with PyTorch models.</p>

<h2 style="color:#3366cc;">🚀 Let's Start Our Workflow</h2>

<h3 style="color:#ff6600;">1️⃣ Create a Custom Dataset Class</h3>
<p>We define a custom dataset class by implementing three main functions: <code>__init__</code>, <code>__len__</code>, and <code>__getitem__</code>.</p>

<h3 style="color:#ff6600;">2️⃣ Create an Object of the Dataset Class</h3>
<p>We instantiate the dataset class to store and manage our data efficiently.</p>

<h3 style="color:#3366cc;">3️⃣ Create an Object of the DataLoader Class</h3>
<p>The DataLoader will help us load the dataset efficiently with batching and shuffling.</p>

<h3 style="color:#ff6600;">4️⃣ Use a Loop to Print or Show the Batches</h3>
<p>Finally, we use a loop to iterate through the DataLoader and display the data in batches.</p>

<hr style="border:2px solid #ff5733; width:80%;">


<h1 style="color:#ff6600;">Simple Code Example for Dataset and DataLoader classes</h1>

<h2 style="color:#3366cc;">Import the Necessary Labraries</h2>

In [58]:
from sklearn.datasets import make_classification
import torch
from torch.utils.data import Dataset, DataLoader

In [2]:
# step 01: create a synthetic classification dataset using sklearn 
X, y = make_classification(
    n_samples=10,          # Number of samples
    n_features=2,          # Number of features
    n_informative=2,       # Number of  inforative features
    n_redundant=0,         # Number of Redundant features (No dulicate )
    n_classes=2,           # Number of classes 
    random_state=42        # For reproductivity
)

In [22]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [23]:
X.shape

(10, 2)

In [24]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [25]:
y.shape

(10,)

In [26]:
# convert the data into pytorch Tensor 
X = torch.tensor(X, dtype = torch.float32)
y = torch.tensor(y, dtype = torch.long)

In [27]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

<h2 style="color:#3366cc;">Let's start our work flow</h2>

In [59]:
# create a custom class in whcih three man functions
class CustomDataSet(Dataset):
# 1:- __init__()
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
        
# 2:- __len__()
    def __len__(self):
        return self.features.shape[0]

# # 3:- __getitem__()
    def __getitem__(self, index):
        return self.features[index], self.labels[index]


In [60]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [61]:
df.iloc[:,1:]

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [62]:
# create an object of the class
dataset = CustomDataSet(df.iloc[:,0], df.iloc[:,1:])

In [63]:
len(dataset)

569

In [65]:
# create the object of DataLoader class
dataloader = DataLoader(df,batch_size=32, shuffle=True)

In [66]:
# Use for loop to print or show the Batches
for batch_features, batch_labels in dataloader:
    print(batch_features),
    print(batch_labels),
    print(len(batch_features))
    print('-'*50)

KeyError: 215

<h1 style="color:#ff6600; text-align:center;">📊 Breast Cancer Dataset Training Pipeline</h1>

<p style="font-size:22px; text-align:center; color:#444;">
The training pipeline consists of the following steps:
</p>
<h2 style="color:#33A1FF; font-size:30px;">📜 Code Flow</h2>


<p style="font-size:22px; text-align:center; color:#444;">
The training pipeline consists of the following steps:
</p>

<ol style="font-size:22px; color:#444;">
    <li>✅ Load the dataset</li>
    <li>✅ Basic preprocessing</li>
    <li>🚀 Training Process:
        <ul>
            <li>✅ Create the model</li>
            <li>🔹 Forward pass</li>
            <li>🔹 Loss calculation</li>
            <li>🔹 Backpropagation</li>
            <li>🔹 Parameter update</li>
        </ul>
    </li>
    <li>📊 Model evaluation</li>
</ol>


<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#ff6600;">📌 Import the Necessary Libraries</h2>
<p>Before we begin, let's import the required libraries for working with datasets and dataloaders in PyTorch.</p>

<h2 style="color:#3366cc;">🔹 Convert the Data into PyTorch Tensors</h2>
<p>We need to convert our data into PyTorch tensors for compatibility with PyTorch models.</p>

<h2 style="color:#ff6600;">🚀 Let's Start Our Workflow</h2>

<h3 style="color:#3366cc;">1️⃣ Create a Custom Dataset Class</h3>
<p>We define a custom dataset class by implementing three main functions: <code>__init__</code>, <code>__len__</code>, and <code>__getitem__</code>.</p>

<h3 style="color:#ff6600;">2️⃣ Create an Object of the Dataset Class</h3>
<p>We instantiate the dataset class to store and manage our data efficiently.</p>

<h3 style="color:#3366cc;">3️⃣ Create an Object of the DataLoader Class</h3>
<p>The DataLoader will help us load the dataset efficiently with batching and shuffling.</p>

<h3 style="color:#ff6600;">4️⃣ Use a Loop to Print or Show the Batches</h3>
<p>Finally, we use a loop to iterate through the DataLoader and display the data in batches.</p>

<hr style="border:2px solid #ff5733; width:80%;">


In [67]:
# import the necessary labraries
import torch
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [55]:
# Read CSV file
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/master/data.csv")

In [68]:
df.drop(columns=['id','Unnamed: 32'], inplace = True)

KeyError: "['id', 'Unnamed: 32'] not found in axis"

In [69]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [70]:
# See the shape of the data 
df.shape

(569, 31)

In [71]:
df = df.apply(pd.to_numeric, errors='coerce')

In [72]:
# split the data into test and train data 
X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:, 1:] , df.iloc[:,0], test_size=0.2)

In [73]:
# Scale the data to same rounding
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [74]:
X_train

array([[-0.53780215,  2.47312964, -0.60713377, ..., -1.72985929,
        -0.74807006, -0.95555932],
       [-0.77699948, -1.04768679, -0.76370698, ..., -0.78447147,
        -1.68121992, -0.55027769],
       [-0.87990996, -0.60085892, -0.86875996, ..., -0.61404339,
         0.17103575, -0.28127498],
       ...,
       [-0.29026073,  0.26706326, -0.33987255, ..., -1.09995111,
        -0.3142646 , -0.54909266],
       [-1.55939726, -0.18678284, -1.54617054, ..., -1.72985929,
         0.39574073, -0.14203349],
       [ 1.44531059,  0.95952949,  1.47299571, ...,  0.61859457,
         0.04932055, -0.43947702]])

In [75]:
# Encode the data to (0,1)
encoder = LabelEncoder()
Y_train = encoder.fit_transform(Y_train)
Y_test = encoder.transform(Y_test)

In [76]:
Y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [77]:
# convert the numpy array into tenser
X_test_tensor = torch.from_numpy(X_test).float()
X_train_tensor = torch.from_numpy(X_train).float()
Y_test_tensor = torch.from_numpy(Y_test).float()
Y_train_tensor = torch.from_numpy(Y_train).float()

In [78]:
X_train_tensor.shape

torch.Size([455, 30])

In [79]:
Y_train_tensor.shape

torch.Size([455])

In [80]:
# create a custom class in whcih three man functions
class CustomDataSet(Dataset):
# 1:- __init__()
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
        
# 2:- __len__()
    def __len__(self):
        return self.features.shape[0]

# # 3:- __getitem__()
    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]


In [81]:
# create object of dataset class
train_dataset = CustomDataSet(X_train_tensor, Y_train_tensor) 
test_dataset = CustomDataSet(X_test_tensor, Y_test_tensor)

In [82]:
train_dataset[10]

(tensor([-0.5990,  0.7771, -0.5536, -0.5984, -1.9270,  0.0459, -0.1286, -0.5055,
         -2.1748,  0.5381, -1.0250,  0.3350, -0.5538, -0.6714, -0.6761,  1.0466,
          0.3377,  0.7176,  0.4462,  1.2715, -0.7714,  0.4891, -0.6018, -0.6961,
         -1.9730,  0.4456,  0.1044, -0.0901, -1.0882,  0.5885]),
 tensor(0.))

In [83]:
# create abject of class Dataloader
train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_dataset = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [84]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super(MySimpleNN, self).__init__()
        self.linear = nn.Linear(num_features, 1)  # must match dataset features
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        z = self.linear(features)
        y_pred = self.sigmoid(z)
        return y_pred

# Instantiate with correct input size (2 features)
model = MySimpleNN(X_train_tensor.shape[1])  # this will be 2


In [85]:
# Define model
import torch.nn as nn
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super(MySimpleNN, self).__init__()
        self.linear = nn.Linear(num_features, 1)  # Linear layer
        self.sigmoid = nn.Sigmoid()  # Sigmoid activation

    def forward(self, features):
        z = self.linear(features)  # Linear transformation
        y_pred = self.sigmoid(z)  # Apply sigmoid
        return y_pred


In [86]:
# important parameters
learning_rate = 0.01
epochs = 15

In [87]:
X_train_tensor.shape[1]

30

In [88]:
Y_train_tensor.dtype == torch.float

True

In [89]:
# Binary cross entropy loss function
Loss = nn.BCELoss()

# use optimazer 
optimazwer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [90]:
# Training Pipline 
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loopabs
for epoch in range(epochs):
    
    # forward pass 
    y_pred = model(batch_features)

    # loss function
    loss = Loss(y_pred,batch_labels.view(-1,1))
    
    # Backward Pass 
    loss.backward()
    
    # Update Parameters
    """ with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad"""
    
    optimazwer.step()

    optimazwer.zero_grad()
    
    print(f'Epoch: {epoch + 1}, Loss:{loss.item()} ')

NameError: name 'batch_features' is not defined

In [114]:
# Model Evaluation
model.eval()    # set the model to evaluate 
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_dataset:
        # forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.5).float()   # convert the probability to binary prediction

        # calculate the accurcy for current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean()
        accuracy_list.append(batch_accuracy)

# calculate overall accuray
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy.item()}')
 

Accuracy: 0.5047619342803955
